# Generated by Django 4.2.1 on 2023-05-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sour_candy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='Recipes',
        ),
    ]
