# Generated by Django 4.2.1 on 2023-05-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sour_candy', '0002_alter_category_table_alter_recipe_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_title',
            new_name='title',
        ),
    ]
