# Generated by Django 4.2.1 on 2023-05-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_candy', '0006_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='images/default-image-food.jpg', null=True, upload_to='images/'),
        ),
    ]
