# Generated by Django 4.2.1 on 2023-05-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_candy', '0010_profile_alter_recipe_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='images/profile/default.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
